# Generated by Django 5.2 on 2025-04-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='accepted_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bid', to='gigs.bid'),
        ),
        migrations.AddField(
            model_name='gig',
            name='payment_deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='payment_released',
            field=models.BooleanField(default=False),
        ),
    ]
